default_connection_name = "advanced_data_engineering_snowflake"

[connections]
[connections.myconnection]
account="KYWCRLT-XTB11086"
user="SMELENDEZ25"
password="Dataengineer25"
warehouse="COMPUTE_WH"
role="ACCOUNTADMIN"

[cli.logs]
save_logs = true
level = "info
